version: 2.1
parameters:
    cache-version:
        type: string
        default: "0.1"=


save_cache_wrapper: &save_cache_wrapper
     key: gradle-wrapper-<< pipeline.parameters.image-tag >>--{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
     paths:
        - ~/.gradle/wrapper/
restore_cache_wrapper: &restore_cache_wrapper
    key: gradle-wrapper-<< pipeline.parameters.image-tag >>--{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

jobs:
  say-hello:
    docker:
      - image: cimg/android:2022.09
    steps:
      - checkout
      - *restore_cache_wrapper
      - run:
          name: "Help"
          command: ./gradlew :help
      - *save_cache_wrapper

  second-step:
      docker:
          - image: cimg/android:2022.09
      steps:
          - checkout
          - *restore_cache_wrapper
          - run:
                name: "Help"
                command: ./gradlew :help
          - *save_cache_wrapper
  third-step:
      docker:
          - image: cimg/android:2022.09
      steps:
          - checkout
          - *restore_cache_wrapper
          - run:
                name: "Help"
                command: ./gradlew :help
          - *save_cache_wrapper
  fourth-step:
      docker:
          - image: cimg/android:2022.09
      steps:
          - checkout
          - *restore_cache_wrapper
          - run:
                name: "Help"
                command: ./gradlew :help
          - *save_cache_wrapper


workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - second-step:
          requires:
            - say-hello
      - third-step:
            requires:
                - say-hello
      - fourth-step:
            requires:
                - say-hello

