version: 2.1
parameters:
  cache-version:
    type: string
    default: "0.1"

save_cache_wrapper: &save_cache_wrapper
  save_cache:
    key: << pipeline.parameters.cache-version >>-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
    paths:
       - ~/.gradle/wrapper/
restore_cache_wrapper: &restore_cache_wrapper
  restore_cache:
    key: << pipeline.parameters.cache-version >>-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}


save_cache_assemble: &save_cache_assemble
    save_cache:
        key: << pipeline.parameters.cache-version >>-assemble-{{ checksum "settings.gradle.kts" }}
        paths:
            - ~/.gradle/caches/modules-2/files-2.1
restore_cache_assemble: &restore_cache_assemble
    restore_cache:
        key: << pipeline.parameters.cache-version >>-assemble-{{ checksum "settings.gradle.kts" }}


jobs:
  say-hello:
    docker:
      - image: cimg/android:2022.09
    steps:
      - checkout
      - <<: *restore_cache_wrapper
      - run:
          name: "Help"
          command: ./gradlew :help
      - <<: *save_cache_wrapper

  second-step:
    docker:
      - image: cimg/android:2022.09
    steps:
      - checkout
      - <<: *restore_cache_wrapper
      - <<: *restore_cache_assemble
      - run:
          name: "Help"
          command: ./gradlew :app:assembleDebug
      - <<: *save_cache_wrapper
      - <<: *save_cache_assemble

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - second-step:
          requires:
            - say-hello
